src/main/java/pl/sda/projekt/controller/AddCarController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.sda.projekt.controller;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.RequestScoped;
import javax.persistence.EntityManager;
import javax.persistence.EntityTransaction;
import pl.sda.projekt.Model.Car;

/**
 *
 * @author marecki
 */
@ManagedBean(name = "addCarController")
@RequestScoped
public class AddCarController {

    private Car car = new Car();
    
    @ManagedProperty(value = "#{dbController}")
    private DbController dbController;
    
    public AddCarController() {
    }
    
    public void addCar() {
        //todo walidacja
        EntityManager em = dbController.getEntityManager();
        EntityTransaction tx = em.getTransaction();

        tx.begin();
        em.persist(this.car);
        tx.commit();
    }

    public Car getCar() {
        return car;
    }

    public void setCar(Car car) {
        this.car = car;
    }

    public DbController getDbController() {
        return dbController;
    }

    public void setDbController(DbController dbController) {
        this.dbController = dbController;
    }
}

src/main/java/pl/sda/projekt/controller/CarListController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.sda.projekt.controller;

import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.RequestScoped;
import javax.persistence.EntityManager;
import javax.persistence.EntityTransaction;
import javax.persistence.Query;
import pl.sda.projekt.Model.Car;

/**
 *
 * @author marecki
 */
@ManagedBean (name = "carListController")
@RequestScoped
public class CarListController {

    @ManagedProperty (value="#{dbController}")
    private DbController dbController;
    
    public CarListController() {
    }
    
    public List<Car> getPostsList() {
        EntityManager em = dbController.getEntityManager();
        Query query = em.createQuery("from Car c");
        return query.getResultList();
    }

    public DbController getDbController() {
        return dbController;
    }

    public void setDbController(DbController dbController) {
        this.dbController = dbController;
    }
    
    public Car showCarDetails(long carId) {
        EntityManager em = dbController.getEntityManager();
        return em.find(Car.class, carId);
    }
    
    public void removeCar(Car car) {
        EntityManager em = dbController.getEntityManager();
        EntityTransaction tx = em.getTransaction();
        
        tx.begin();
        em.remove(car);
        tx.commit();
    }
}

src/main/java/pl/sda/projekt/controller/DbController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.sda.projekt.controller;

import java.io.Serializable;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

/**
 *
 * @author Marek
 */
@ManagedBean(name = "dbController")
@SessionScoped
public class DbController implements Serializable {

    private final EntityManagerFactory emf;
    private final EntityManager em;

    public DbController() {
        emf = Persistence.createEntityManagerFactory("pu");
        em = emf.createEntityManager();
    }

    public EntityManager getEntityManager() {
        return em;
    }
}

src/main/java/pl/sda/projekt/controller/RaportController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pl.sda.projekt.controller;

import java.util.Date;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;

/**
 *
 * @author marecki
 */
@ManagedBean (name = "raportController")
@RequestScoped
public class RaportController {

    private Date beginDate = new Date();
    private Date endDate;

    public Date getBeginDate() {
        return beginDate;
    }

    public void setBeginDate(Date beginDate) {
        this.beginDate = beginDate;
    }

    public Date getEndDate() {
        return endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
}

src/main/webapp/add_car.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html">

    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <ui:composition template="templates/common_layout.xhtml">
            <ui:define name ="content">
                <h:form>
                    <div class="row">
                        <div class="col-md-3">Marka</div>
                        <div class="col-md-3"><h:inputText value="#{addCarController.car.brand}"/></div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">Model</div>
                        <div class="col-md-3"><h:inputText value="#{addCarController.car.model}"/></div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">Rocznik</div>
                        <div class="col-md-3"><h:inputText value="#{addCarController.car.yearOfProduction}"/></div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">Przebieg</div>
                        <div class="col-md-3"><h:inputText value="#{addCarController.car.mileage}"/></div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">Silnik</div>
                        <div class="col-md-3"><h:inputText value="#{addCarController.car.engine}"/></div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">Typ paliwa</div>
                        <div class="col-md-3"><h:inputText value="#{addCarController.car.fuelType}"/></div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">Moc</div>
                        <div class="col-md-3"><h:inputText value="#{addCarController.car.horsePower}"/></div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">Skrzynia biegów</div>
                        <div class="col-md-3"><h:inputText value="#{addCarController.car.gearType}"/></div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">Opis</div>
                        <div class="col-md-3"><h:inputText value="#{addCarController.car.description}"/></div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">Cena</div>
                        <div class="col-md-3"><h:inputText value="#{addCarController.car.price}"/></div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">Numer VIN</div>
                        <div class="col-md-3"><h:inputText value="#{addCarController.car.vin}"/></div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">Numer ubezpieczenia</div>
                        <div class="col-md-3"><h:inputText value="#{addCarController.car.insurancePolicy}"/></div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">Numer rejestracyjny</div>
                        <div class="col-md-3"><h:inputText value="#{addCarController.car.registrationDocument}"/></div>
                    </div>
                    <div class="row">
                        <div class="col-md-3"><h:commandButton value="Dodaj samochód" action="#{addCarController.addCar()}"/></div>
                    </div>
                </h:form>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

src/main/webapp/car_details.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <ui:composition template="templates/common_layout.xhtml">
            <ui:define name ="content">
                <h1>#{carListController.showCarDetails(param['id']).brand}
                #{carListController.showCarDetails(param['id']).model}</h1>
                <p>Rocznik #{carListController.showCarDetails(param['id']).yearOfProduction}</p>
                <p>Przebieg #{carListController.showCarDetails(param['id']).mileage}</p>
                <p>Przebieg #{carListController.showCarDetails(param['id']).mileage}</p>
                <p>Silnik #{carListController.showCarDetails(param['id']).engine}</p>
                <p>Typ paliwa #{carListController.showCarDetails(param['id']).fuelType}</p>
                <p>Moc #{carListController.showCarDetails(param['id']).horsePower}</p>
                <p>Skrzynia biegów #{carListController.showCarDetails(param['id']).gearType}</p>
                <p>Opis samochodu #{carListController.showCarDetails(param['id']).description}</p>
                <h1>Cena #{carListController.showCarDetails(param['id']).price}</h1>

                <h:button value="Powrót" outcome="cars_to_sale.html"/>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

src/main/webapp/cars_to_sale.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui = "http://java.sun.com/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
          
    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <ui:composition template="templates/common_layout.xhtml">
            <ui:define name ="content">
                <h:dataTable value="#{carListController.postsList}" var="car" class="table table-striped table-bordered table-hover table-condensed">
                    <h:column>
                        <f:facet name="header">Zdjęcie</f:facet>
                            #{car.model}
                    </h:column>
                    <h:column>
                        <f:facet name="header">Marka</f:facet>
                            #{car.brand}
                    </h:column>
                    <h:column>
                        <f:facet name="header">Model</f:facet>
                            #{car.model}
                    </h:column>
                    <h:column>
                        <f:facet name="header">Rok</f:facet>
                            #{car.yearOfProduction}
                    </h:column>
                    <h:column>
                        <f:facet name="header">Przebieg</f:facet>
                            #{car.mileage}
                    </h:column>
                    <h:column>
                        <f:facet name="header">Cena</f:facet>
                            #{car.price}
                    </h:column>
                    <h:column>
                        <f:facet name="header">Wyświetl szczegóły</f:facet>
                        <h:form>
                            <h:button value="Szczegóły" outcome="car_details.xml?id=#{car.id}"/>
                        </h:form>
                    </h:column>
                    <h:column>
                        <f:facet name="header">Usuń samochód</f:facet>
                        <h:form>
                            <h:commandButton value="Usuń" action="#{carListController.removeCar(car)}"/>
                        </h:form>
                    </h:column>
                </h:dataTable>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

src/main/webapp/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui = "http://java.sun.com/jsf/facelets">

    <h:head>
        <title>Facelet Title</title>
    </h:head>
    <h:body>
        <ui:composition template="templates/common_layout.xhtml">
            <ui:define name ="content">
                <h1>Komis samochodowy "U Janusza"</h1>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

src/main/webapp/raports.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    
    <h:head>
        <title>Facelet Title</title>
        <script name="jquery/jquery.js" library="primefaces"></script>
    </h:head>
    <h:body>
        <ui:composition template="templates/common_layout.xhtml">
            <ui:define name ="content">

            </ui:define>
        </ui:composition>
    </h:body>
</html>

src/main/webapp/templates/common_layout.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">

    <h:head>
        <!-- Bootstrap core CSS -->
        <link href="css/bootstrap.min.css" rel="stylesheet"/>
        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <link href="css/ie10-viewport-bug-workaround.css" rel="stylesheet"/>
        <!-- Custom styles for this template -->
        <link href="css/starter-template.css" rel="stylesheet"/>

        <link href="css/sticky-footer.css" rel="stylesheet"/>
    </h:head>
    <h:body>
        <div class="container">
            <div class="starter-template" style="padding-top: 50px">
                <ui:insert name="header">
                    <ui:include src="header.xhtml"/>
                </ui:insert>
                <ui:insert name="content">
                    <ui:include src="content.xhtml"/>
                </ui:insert>
            </div>
        </div>
        <!-- Bootstrap core JavaScript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script type="text/javascript" src="js/bootstrap.min.js"></script>
        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <script type="text/javascript" src="js/ie10-viewport-bug-workaround.js"></script>
    </h:body>
</html>

src/main/webapp/templates/content.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">

    <h:body>
        <ui:composition>
            <h1>CONTENT!</h1>
        </ui:composition>
    </h:body>
</html>

src/main/webapp/templates/header.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">

    <h:body>
        <ui:composition>
            <nav class="navbar navbar-inverse navbar-fixed-top">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="index.xhtml">Komis samochodowy</a>
                    </div>
                    <div id="navbar" class="collapse navbar-collapse">
                        <ul class="nav navbar-nav">
                            <li><h:link value="Samochody" outcome="cars_to_sale.xhtml"/></li>
                            <li><h:link value="Dodaj samochód" outcome="add_car.xhtml"/></li>
                            <li><h:link value="Raporty" outcome="raports.xhtml"/></li>
                        </ul>
                    </div>
                </div>
            </nav>
        </ui:composition>
    </h:body>
</html>